//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBill
    {
        public string PB { get; set; }
        public Nullable<int> Bid { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual UPI UPI { get; set; }
    }
}
