//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRoomBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentBills = new HashSet<PaymentBill>();
        }

        public int PId { get; set; }
        [Required]
        public string Account_HName { get; set; }
      [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Card Number contains only digits")]      
        public Nullable<long> Card_Number { get; set; }
        [Required]
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = "CVV contains only digits")]    
        public Nullable<int> cvv { get; set; }
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBill> PaymentBills { get; set; }
    }
}
